const speakers = [
  {
    name: "Cem Özer",
    organization: "Sovereign Labs",
    image: require("./photos/cem.jpg").default,
    twitter: "https://twitter.com/cemozer_",
  },
  {
    name: "Gülcan Yayla",
    organization: "Patika.dev & Rise In",
    image: require("./photos/gulcan.jpg").default,
    twitter: "https://twitter.com/gulcan_yayla",
  },
  {
    name: "Vitalik Buterin",
    organization: "Ethereum Foundation",
    image: require("./photos/vitalik.jpg").default,
    twitter: "https://twitter.com/VitalikButerin",
  },
  {
    name: "Aya Miyaguchi",
    organization: "Ethereum Foundation",
    image: require("./photos/aya.jpeg").default,
    twitter: "https://twitter.com/AyaMiyagotchi",
  },
  {
    name: "Şant Manukyan",
    organization: "İş Yatırım",
    image: require("./photos/sant.jpg").default,
    twitter: "https://twitter.com/SantManukyan",
  },
  {
    name: "Emre Tekişalp",
    organization: "O(1) Labs",
    image: require("./photos/emre.jpeg").default,
    twitter: "https://twitter.com/etekis",
  },
  {
    name: "Efe Bulduk",
    organization: "FirstBatch",
    image: require("./photos/efe.jpg").default,
    twitter: "https://twitter.com/TheBullduck",
  },
  {
    name: "Cem Dağdelen",
    organization: "Giza",
    image: require("./photos/cemD.jpeg").default,
    twitter: "https://twitter.com/CemFDagdelen",
  },
  {
    name: "Baki Er",
    organization: "Clave",
    image: require("./photos/baki.jpg").default,
    twitter: "https://twitter.com/LibraryDefi",
  },
  {
    name: "Mindy Harrell",
    organization: "CoW Protocol",
    image: require("./photos/mindy.jpeg").default,
    twitter: "https://twitter.com/Silver_Queen",
  },
  {
    name: "Turan Sert",
    organization: "Araştırmacı",
    image: require("./photos/turan.png").default,
    twitter: "https://twitter.com/turansert",
  },
  {
    name: "İsa Sertkaya",
    organization: "Silent Protocol",
    image: require("./photos/isa.jpeg").default,
    twitter: "https://twitter.com/isa_sertkaya",
  },
  {
    name: "Furkan Akal",
    organization: "Detable",
    image: require("./photos/furkan.jpg").default,
    twitter: "https://twitter.com/furkanakalcom",
  },
  {
    name: "Erkan Gül",
    organization: "Moseiki",
    image: require("./photos/erkan.jpg").default,
    twitter: "https://twitter.com/_ErkanG",
  },
  {
    name: "Ali Tıknazoğlu",
    organization: "Phaver",
    image: require("./photos/ali.jpg").default,
    twitter: "https://twitter.com/alitiknazoglu",
  },
  {
    name: "Mesut Gülecen",
    organization: "Kaira",
    image: require("./photos/mesut.jpeg").default,
    twitter: "https://twitter.com/mesutgulecen",
  },
  {
    name: "Elçin Karatay",
    organization: "Solak & Partners",
    image: require("./photos/elcin.jpeg").default,
    twitter: "https://twitter.com/elcin_karatay",
  },
  {
    name: "Erdem Mümtaz Hacıpaşaoğlu",
    organization: "Vircon Legal",
    image: require("./photos/mumtaz.jpeg").default,
    twitter: "https://twitter.com/MumtazHcpsglu",
  },
  {
    name: "Ahmet Özcan",
    organization: "Semiotic Labs",
    image: require("./photos/ahmet.jpeg").default,
    twitter: "https://twitter.com/ahmet_s_ozcan",
  },
  {
    name: "Mert Sağlam",
    organization: "KimlikDAO",
    image: require("./photos/mert.jpeg").default,
    twitter: "https://twitter.com/szaglam",
  },
  {
    name: "Ekrem Bal",
    organization: "Chainway",
    image: require("./photos/ekrem.jpeg").default,
    twitter: "https://twitter.com/ekrembal_",
  },
  {
    name: "Doğan Alpaslan",
    organization: "Clave",
    image: require("./photos/dogan.jpg").default,
    twitter: "https://twitter.com/DoganEth",
  },
  {
    name: "Atakan Yavuzarslan",
    organization: "Go+ Security",
    image: require("./photos/atakan.jpeg").default,
    twitter: "https://twitter.com/theyavuzarslan",
  },
]

export default speakers
